name: ci

on:
  push:
    branches: [ dev,master ]
    tags: [ '*' ]
  pull_request:
    branches: [ dev,master ]
  # workflow_dispatch:
    # branches: [ dev,master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: src/github.com/myroslav-b/olimp

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Test
      run: |
        go get -u -t ./...
        go test -v ./...
      env:
        GOPATH: "/home/runner/work/olimp/olimp"
      working-directory: src/github.com/myroslav-b/olimp/cmd/olimp

    - name: Build
      run: |
        go get -u ./...
        go build -v
      env:
        GOPATH: "/home/runner/work/olimp/olimp"
      working-directory: src/github.com/myroslav-b/olimp/cmd/olimp

    - name: Build pr image
      if: github.event_name == 'pull_request'
      run: |
        docker build -t docker.pkg.github.com/myroslav-b/olimp/olimp:latest ./src/github.com/myroslav-b/olimp

    - name: Build and push dev image
      if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
      run: |
        docker build -t docker.pkg.github.com/myroslav-b/olimp/olimp:dev ./src/github.com/myroslav-b/olimp
        docker login https://docker.pkg.github.com --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PAT }}
        docker push docker.pkg.github.com/myroslav-b/olimp/olimp:dev

    - name: Build and push master image
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        docker build -t docker.pkg.github.com/myroslav-b/olimp/olimp:master ./src/github.com/myroslav-b/olimp
        docker login https://docker.pkg.github.com --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PAT }}
        docker push docker.pkg.github.com/myroslav-b/olimp/olimp:master

    - name: Build and push tagged image
      if: github.event_name == 'push' && github.event.ref_type == 'tag'
      run: |
        GIT_TAG="${GITHUB_REF#refs/tags/}"
        docker build -t docker.pkg.github.com/myroslav-b/olimp/olimp:${GIT_TAG} ./src/github.com/myroslav-b/olimp
        docker login https://docker.pkg.github.com --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PAT }}
        docker push docker.pkg.github.com/myroslav-b/olimp/olimp:${GIT_TAG}
        docker tag docker.pkg.github.com/myroslav-b/olimp/olimp:${GIT_TAG} umputun/secrets:latest
        docker push docker.pkg.github.com/myroslav-b/olimp/olimp:latest
